[package]
name = "synth_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyboard_matrix = { path = "../keyboard_matrix" }

[dev-dependencies]
more-asserts = "0.3.1"