[package]
edition = "2021"
name = "keyboard_matrix"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = {version = "0.2.7", features = ["unproven"]}

[dev-dependencies]
more-asserts = "0.3.1"
